# Generated by Django 6.1 on 2026-08-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(max_length=150)),
                ('role_type', models.CharField(max_length=150)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('stipend_available', models.BooleanField(default=False)),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='companies.companyprofile')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='locations.district')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
