# Generated by Django 6.1 on 2026-09-06 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(max_length=150)),
                ('role_type', models.CharField(max_length=150)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('education_level', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Level 4 — Certificate'), (5, 'Level 5 — Technician Certificate'), (6, 'Level 6 — Ordinary Diploma'), (7, 'Level 7 — Higher Diploma'), (8, "Level 8 — Bachelor's Degree"), (9, "Level 9 — Master's Degree"), (10, 'Level 10 — Doctorate (PhD)')], help_text='Minimum TCU qualification level required (Level 4 Certificate to Level 10 PhD).', null=True)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('stipend_available', models.BooleanField(default=False)),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='companies.companyprofile')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='locations.district')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
