# Generated by Django 6.1 on 2026-08-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_acceptance_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(db_index=True, max_length=30)),
                ('record_id', models.PositiveBigIntegerField()),
                ('record_hash', models.CharField(max_length=64)),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['record_type', 'record_id'], name='core_integr_record__dec904_idx')],
            },
        ),
    ]
