# Generated by Django 6.1 on 2026-08-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('locations', '0002_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='locations.ward'),
        ),
    ]
