# Generated by Django 6.1 on 2026-09-06 11:55

import apps.applications.models
import apps.documents.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slots', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='PENDING', max_length=20)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('company_message', models.TextField(blank=True)),
                ('student_message', models.TextField(blank=True)),
                ('application_letter', models.FileField(blank=True, null=True, upload_to=apps.applications.models.application_letter_upload_path, validators=[apps.documents.validators.validate_upload])),
                ('letter_original_name', models.CharField(blank=True, max_length=255)),
                ('letter_sha256', models.CharField(blank=True, max_length=64)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='slots.slot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'slot'), name='uniq_student_slot_application')],
            },
        ),
    ]
