# Generated by Django 6.1 on 2026-08-16 06:58

import apps.applications.models
import apps.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_status_rework_pending_paid_unpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_letter',
            field=models.FileField(blank=True, null=True, upload_to=apps.applications.models.application_letter_upload_path, validators=[apps.documents.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='application',
            name='letter_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
