# Generated by Django 6.1 on 2026-08-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_application_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='letter_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
