# Generated by Django 6.1 on 2026-08-15 07:50

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('STUDENT_ID', 'Student ID Card'), ('RESULTS_MATRIX', 'Semester Results Matrix'), ('CV', 'Curriculum Vitae'), ('INTRO_LETTER', 'University Introduction Letter'), ('BRELA_CERT', 'BRELA Registration Certificate'), ('TIN_CERT', 'TIN Certificate'), ('BUSINESS_LICENSE', 'Business License')], max_length=30)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
