# Generated by Django 6.1 on 2026-08-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='scan_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='scan_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('ERROR', 'Error')], default='PENDING', help_text='Result of the async deep file scan (Celery).', max_length=20),
        ),
    ]
