# Generated by Django 6.1 on 2026-09-06 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(blank=True, help_text='Your university registration number, e.g. 2022-04-01234', max_length=40)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Select your gender.', max_length=10)),
                ('profile_photo', models.ImageField(blank=True, help_text='A clear headshot photo (max 2MB).', null=True, upload_to='profile_photos/')),
                ('id_card_photo', models.ImageField(blank=True, help_text='A clear photo of your student ID card (max 2MB).', null=True, upload_to='id_cards/')),
                ('university', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('current_year', models.PositiveSmallIntegerField()),
                ('education_level', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Level 4 — Certificate'), (5, 'Level 5 — Technician Certificate'), (6, 'Level 6 — Ordinary Diploma'), (7, 'Level 7 — Higher Diploma'), (8, "Level 8 — Bachelor's Degree"), (9, "Level 9 — Master's Degree"), (10, 'Level 10 — Doctorate (PhD)')], help_text='Your TCU qualification level (Level 4 Certificate to Level 10 PhD).', null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='locations.district')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='locations.region')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='locations.ward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
