# Generated by Django 6.1 on 2026-09-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='current_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
