# Generated by Django 6.1 on 2026-08-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='A clear headshot photo (max 2MB).', null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='Your university registration number, e.g. 2022-04-01234', max_length=40),
        ),
    ]
