# Generated by Django 6.1 on 2026-08-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='id_card_photo',
            field=models.ImageField(blank=True, help_text='A clear photo of your student ID card (max 2MB).', null=True, upload_to='id_cards/'),
        ),
    ]
