# Generated by Django 6.1 on 2026-09-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_current_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_year',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First Year / Year 1'), (2, 'Second Year / Year 2'), (3, 'Third Year / Year 3')], help_text='Required if Higher Diploma is selected', null=True),
        ),
    ]
