# Generated by Django 6.1 on 2026-09-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_studentprofile_current_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='reapplication_credit',
            field=models.BooleanField(default=False),
        ),
    ]
