# Generated by Django 6.1 on 2026-08-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_id_card_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Select your gender.', max_length=10),
        ),
    ]
