# Generated by Django 6.1 on 2026-08-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_ward'),
        ('students', '0004_studentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='locations.ward'),
        ),
    ]
