# Generated by Django 6.1 on 2026-08-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='education_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Level 4 — Certificate'), (5, 'Level 5 — Technician Certificate'), (6, 'Level 6 — Ordinary Diploma'), (7, 'Level 7 — Higher Diploma'), (8, "Level 8 — Bachelor's Degree"), (9, "Level 9 — Master's Degree"), (10, 'Level 10 — Doctorate (PhD)')], help_text='Your TCU qualification level (Level 4 Certificate to Level 10 PhD).', null=True),
        ),
    ]
