# Generated by Django 6.1 on 2026-08-15 07:50

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(default=apps.payments.models.generate_reference_id, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('method', models.CharField(choices=[('M_PESA', 'M-Pesa'), ('TIGO_PESA', 'Tigo Pesa'), ('AIRTEL_MONEY', 'Airtel Money')], max_length=15)),
                ('gateway', models.CharField(choices=[('MOCK', 'Mock Simulator'), ('SELCOM', 'Selcom'), ('PESAPAL', 'Pesapal')], default='MOCK', max_length=15)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=100)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='applications.application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_id'], name='payments_pa_referen_7b9331_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
    ]
